import { DoCheck, TemplateRef } from "@angular/core";
import type { ApplicableRegulatoryObligationRecord, AuditLogRecord, AuthSession, BillingFollowUpStatus, BillingCustomerRecord, BillingCustomerType, CockpitSummaryRecord, BuildingSafetyAlertRecord, BuildingSafetyItemRecord, BuildingSafetyItemStatus, BuildingSafetyItemType, ComplianceStatus, DocumentLifecycleStatus, DuerpEntryRecord, DuerpSeverity, InvoiceRecord, InvoiceStatus, MembershipAccess, ModuleCode, OrganizationRegulatoryProfileRecord, OrganizationRecord, OrganizationSiteLocationEnrichmentErrorReason, OrganizationSiteRecord, OrganizationSiteType, RegulatoryEvidenceLinkKind, RegulatoryEvidenceRecord, RegulatoryCriterionRecord, RegulatoryObligationCategory, RegulatoryObligationPriority, QuoteRecord, QuoteStatus, WorksiteApiSummary, WorksiteAssigneeRecord, WorksiteCoordinationStatus, WorksiteDocumentRecord, WorksiteProofRecord, WorksiteSignatureRecord } from "@conformeo/contracts";
import { type CfmTone } from "@conformeo/ui";
import { type DesktopHomeSiteEnrichmentState, type DesktopShellContext, type WorkspaceTemplateName } from "./desktop-shell-context";
import * as i0 from "@angular/core";
type HasEmployeesValue = "" | "yes" | "no";
type BillingLineForm = {
    description: string;
    quantity: string;
    unitPrice: string;
};
type QuoteDraftForm = {
    customerId: string;
    worksiteId: string;
    title: string;
    issueDate: string;
    validUntil: string;
    status: QuoteStatus;
    notes: string;
    lines: BillingLineForm[];
};
type InvoiceDraftForm = {
    customerId: string;
    worksiteId: string;
    title: string;
    issueDate: string;
    dueDate: string;
    status: InvoiceStatus;
    notes: string;
    lines: BillingLineForm[];
};
type WorksitePreventionPlanForm = {
    usefulDate: string;
    interventionContext: string;
    vigilancePoints: string;
    measurePoints: string;
    additionalContact: string;
};
type WorksitePreventionPlanPreview = {
    companyName: string;
    worksiteName: string;
    worksiteAddress: string;
    clientName: string | null;
    usefulDateLabel: string | null;
    interventionContext: string;
    vigilancePoints: string[];
    measurePoints: string[];
    additionalContact: string | null;
};
type CoordinationDraftForm = {
    status: WorksiteCoordinationStatus;
    assigneeUserId: string;
    commentText: string;
};
type DashboardKpiCard = {
    id: string;
    label: string;
    value: string;
    detail: string;
    statusLabel: string;
    tone: CfmTone;
};
type DashboardAlertItem = {
    id: string;
    title: string;
    description: string;
    moduleLabel: string;
    tone: CfmTone;
    priority: number;
};
type DashboardActionModule = "reglementation" | "chantier" | "facturation";
type DashboardActionModuleFilter = "all" | DashboardActionModule;
type DashboardActionPriority = "high" | "medium" | "low";
type CoordinationStatusFilter = "all" | WorksiteCoordinationStatus;
type CoordinationAssigneeFilter = "all" | "unassigned" | string;
type WorksiteDocumentLifecycleFilter = "all" | DocumentLifecycleStatus;
type BetaFeedbackCategory = "blocking" | "unclear" | "improvement" | "positive";
type BetaFeedbackArea = "cockpit" | "worksite" | "worksite_document" | "facturation" | "reglementation" | "sync" | "other";
type DashboardActionItem = {
    id: string;
    module: DashboardActionModule;
    priority: DashboardActionPriority;
    title: string;
    description: string;
    context: string | null;
};
type RegulatoryShowcaseSummary = {
    statusLabel: string;
    tone: CfmTone;
    headline: string;
    summary: string;
    context: string | null;
    scoreSummary: string;
    profileLabel: string;
    profileTone: CfmTone;
    siteLabel: string | null;
    siteTone: CfmTone;
};
type RegulatoryShowcaseActionKind = "scroll" | "site_enrichment";
type RegulatoryScoreDriverItem = {
    id: string;
    label: string;
    detail: string;
    statusLabel: string;
    tone: CfmTone;
};
type RegulatoryShowcasePriorityItem = {
    id: string;
    title: string;
    familyLabel: string;
    levelLabel: string;
    tone: CfmTone;
    impact: string;
    context: string | null;
    focusLabel: string | null;
    actionLabel: string;
    actionKind: RegulatoryShowcaseActionKind;
    sectionId: string;
    obligationId: string | null;
    siteId: string | null;
    rank: number;
};
type RegulatoryShowcaseFamilyCard = {
    id: RegulatoryObligationCategory;
    label: string;
    countLabel: string;
    detail: string;
    statusLabel: string;
    tone: CfmTone;
    highlights: Array<{
        label: string;
        value: string;
    }>;
    actionLabel: string;
    actionKind: RegulatoryShowcaseActionKind;
    sectionId: string;
    obligationId: string | null;
    siteId: string | null;
};
type RegulatoryShowcaseActionItem = {
    id: string;
    title: string;
    detail: string;
    supportLabel: string | null;
    actionLabel: string;
    tone: CfmTone;
    actionKind: RegulatoryShowcaseActionKind;
    sectionId: string;
    obligationId: string | null;
    siteId: string | null;
};
type RegulatoryShowcaseEvidenceItem = {
    id: string;
    title: string;
    detail: string;
    statusLabel: string;
    tone: CfmTone;
    contextLabel: string | null;
};
type RegulatoryAllSiteSourceKind = "declared" | "duerp" | "building_safety" | "evidence";
type RegulatoryAllSiteItem = {
    key: string;
    siteId: string | null;
    name: string;
    address: string | null;
    declaredSite: OrganizationSiteRecord | null;
    sourceKinds: RegulatoryAllSiteSourceKind[];
};
type DashboardPerspectiveCard = {
    id: string;
    label: string;
    headline: string;
    detail: string;
    highlights: Array<{
        id: string;
        label: string;
        value: string;
    }>;
    statusLabel: string;
    tone: CfmTone;
};
type DashboardWorksiteOverviewItem = {
    id: string;
    name: string;
    summary: string;
    operationalSummary: string;
    taskSummary: string;
    coordination: DashboardCoordinationState;
    worksiteDocuments: DashboardWorksiteDocumentItem[];
    linkedQuotesSummary: string;
    linkedInvoicesSummary: string;
    linkedWorksiteDocumentsSummary: string;
    worksiteDocumentsCount: number;
    financialSummary: string | null;
    regulatorySummary: string | null;
    statusLabel: string;
    statusTone: CfmTone;
    signalLabel: string;
    signalTone: CfmTone;
};
type DashboardCoordinationState = {
    status: WorksiteCoordinationStatus;
    statusLabel: string;
    statusTone: CfmTone;
    assigneeUserId: string | null;
    assigneeDisplayName: string | null;
    assigneeLabel: string;
    commentText: string | null;
    commentSummary: string;
    updatedAtLabel: string | null;
};
type DashboardWorksiteDocumentItem = {
    id: string;
    title: string;
    documentType: string;
    fileName: string;
    worksiteId: string;
    worksiteName: string;
    lifecycleStatus: DocumentLifecycleStatus;
    lifecycleStatusLabel: string;
    lifecycleStatusTone: CfmTone;
    technicalStatusLabel: string;
    technicalStatusTone: CfmTone;
    typeLabel: string;
    proofCount: number;
    proofCountLabel: string;
    signatureStatusLabel: string;
    signatureStatusTone: CfmTone;
    linkedSignature: DashboardWorksiteLinkedAssetItem | null;
    linkedSignatureId: string | null;
    linkedSignatureLabel: string | null;
    linkedSignatureDetail: string | null;
    linkedProofs: DashboardWorksiteLinkedAssetItem[];
    linkedProofsSummary: string | null;
    hasStoredFile: boolean;
    fileAvailabilityLabel: string;
    fileAvailabilityTone: CfmTone;
    fileSizeLabel: string | null;
    uploadedAtValue: string | null;
    uploadedAtLabel: string | null;
    notes: string | null;
    coordination: DashboardCoordinationState;
};
type DashboardWorksiteLinkedAssetItem = {
    id: string;
    label: string;
    detail: string | null;
    statusLabel: string;
    statusTone: CfmTone;
};
type DashboardCoordinationTodoItem = {
    id: string;
    kind: "worksite" | "document";
    kindLabel: string;
    kindTone: CfmTone;
    title: string;
    description: string;
    context: string | null;
    status: WorksiteCoordinationStatus;
    statusLabel: string;
    statusTone: CfmTone;
    worksiteId: string;
    documentId: string | null;
};
type DashboardCustomerOverviewItem = {
    id: string;
    name: string;
    summary: string;
    context: string;
    statusLabel: string;
    statusTone: CfmTone;
    signalLabel: string;
    signalTone: CfmTone;
};
export declare class AppComponent implements DoCheck, DesktopShellContext {
    private static readonly REGULATORY_WORKSPACE_SEGMENT_LABELS;
    private static readonly DISABLE_BOOTSTRAP_SESSION_RESTORE;
    private static readonly DISABLE_DO_CHECK_PERSISTENCE;
    private static readonly WORKSPACE_LOADING_DISABLED;
    private static readonly WORKSPACE_DEBUG_ONLY_LABEL;
    private static readonly DISABLE_DEFERRED_WORKSPACE_SCROLL;
    private readonly router;
    email: string;
    password: string;
    loading: boolean;
    errorMessage: string;
    feedbackMessage: string;
    session: AuthSession | null;
    accessToken: string | null;
    selectedOrganizationId: string | null;
    sessionRestoreInProgress: boolean;
    organizationWorkspaceLoading: boolean;
    private workspaceRefreshInFlight;
    private workspaceRefreshScheduledHandle;
    private workspaceRefreshScheduledOrganizationId;
    private workspaceRefreshScheduledReason;
    private workspaceHydratedOrganizationId;
    private workspaceSegmentIssues;
    regulatoryExporting: boolean;
    organizationProfileSaving: boolean;
    organizationSiteSaving: boolean;
    organizationSiteStatusBusyId: string | null;
    organizationSiteEnrichmentBusyId: string | null;
    homeSiteQuickCreateOpen: boolean;
    organizationProfile: OrganizationRecord | null;
    organizationSites: OrganizationSiteRecord[];
    regulatoryProfile: OrganizationRegulatoryProfileRecord | null;
    selectedObligationId: string | null;
    customerSaving: boolean;
    customerEditingId: string | null;
    customerSearchTerm: string;
    billingCustomers: BillingCustomerRecord[];
    billingWorksites: WorksiteApiSummary[];
    worksiteDocuments: WorksiteDocumentRecord[];
    worksiteProofs: WorksiteProofRecord[];
    worksiteSignatures: WorksiteSignatureRecord[];
    worksiteAssignees: WorksiteAssigneeRecord[];
    selectedWorksiteCoordinationId: string | null;
    selectedCoordinationStatusFilter: CoordinationStatusFilter;
    selectedCoordinationAssigneeFilter: CoordinationAssigneeFilter;
    selectedWorksiteDocumentFilterId: string;
    selectedWorksiteDocumentTypeFilter: string;
    selectedWorksiteDocumentLifecycleFilter: WorksiteDocumentLifecycleFilter;
    selectedWorksiteDocumentDetailId: string | null;
    worksiteDocumentDownloadBusyId: string | null;
    worksiteDocumentPdfBusyId: string | null;
    worksiteCoordinationBusyId: string | null;
    worksiteDocumentCoordinationBusyId: string | null;
    worksiteDocumentStatusBusyId: string | null;
    worksiteDocumentProofBusyId: string | null;
    worksiteDocumentSignatureBusyId: string | null;
    worksitePreventionPlanPdfBusyId: string | null;
    worksitePreventionPlanEditingId: string | null;
    worksiteCoordinationDrafts: Record<string, CoordinationDraftForm>;
    worksiteDocumentCoordinationDrafts: Record<string, CoordinationDraftForm>;
    worksitePreventionPlanForm: WorksitePreventionPlanForm;
    private worksitePreventionPlanInitialForm;
    private billingDraftsHydratedScope;
    private quoteDraftSnapshot;
    private invoiceDraftSnapshot;
    quoteSaving: boolean;
    quoteEditingSaving: boolean;
    quoteEditingId: string | null;
    quoteStatusBusyId: string | null;
    quoteFollowUpBusyId: string | null;
    quoteWorksiteBusyId: string | null;
    quoteDuplicateBusyId: string | null;
    quotePdfBusyId: string | null;
    quoteHistoryBusyId: string | null;
    quoteHistoryOpenId: string | null;
    quoteHistoryById: Record<string, AuditLogRecord[]>;
    quotes: QuoteRecord[];
    invoiceSaving: boolean;
    invoiceEditingSaving: boolean;
    invoiceEditingId: string | null;
    invoiceStatusBusyId: string | null;
    invoiceFollowUpBusyId: string | null;
    invoicePaymentBusyId: string | null;
    invoicePaymentId: string | null;
    invoiceWorksiteBusyId: string | null;
    invoicePdfBusyId: string | null;
    invoiceHistoryBusyId: string | null;
    invoiceHistoryOpenId: string | null;
    invoiceHistoryById: Record<string, AuditLogRecord[]>;
    invoices: InvoiceRecord[];
    cockpitSummary: CockpitSummaryRecord | null;
    buildingSafetySaving: boolean;
    buildingSafetyStatusBusyId: string | null;
    buildingSafetyEditingId: string | null;
    buildingSafetyItems: BuildingSafetyItemRecord[];
    buildingSafetyAlerts: BuildingSafetyAlertRecord[];
    duerpSaving: boolean;
    duerpStatusBusyId: string | null;
    duerpEditingId: string | null;
    duerpEntries: DuerpEntryRecord[];
    regulatoryEvidenceSaving: boolean;
    regulatoryEvidences: RegulatoryEvidenceRecord[];
    selectedSafetySiteId: string;
    selectedDashboardActionModule: DashboardActionModuleFilter;
    betaFeedbackCategory: BetaFeedbackCategory;
    betaFeedbackArea: BetaFeedbackArea;
    betaFeedbackMessageText: string;
    betaFeedbackNotice: string;
    betaFeedbackError: string;
    betaFeedbackCopyBusy: boolean;
    profileForm: {
        name: string;
        legalName: string;
        activityLabel: string;
        employeeCount: string;
        hasEmployees: HasEmployeesValue;
        receivesPublic: HasEmployeesValue;
        storesHazardousProducts: HasEmployeesValue;
        performsHighRiskWork: HasEmployeesValue;
        contactEmail: string;
        contactPhone: string;
        headquartersAddress: string;
        notes: string;
    };
    siteForm: {
        name: string;
        address: string;
        siteType: OrganizationSiteType;
    };
    customerForm: {
        name: string;
        customerType: BillingCustomerType;
        email: string;
        phone: string;
        address: string;
        notes: string;
    };
    quoteForm: {
        customerId: string;
        worksiteId: string;
        title: string;
        issueDate: string;
        validUntil: string;
        status: QuoteStatus;
        notes: string;
        lines: BillingLineForm[];
    };
    quoteEditForm: QuoteDraftForm;
    invoiceForm: {
        customerId: string;
        worksiteId: string;
        title: string;
        issueDate: string;
        dueDate: string;
        status: InvoiceStatus;
        notes: string;
        lines: BillingLineForm[];
    };
    invoiceEditForm: InvoiceDraftForm;
    invoicePaymentForm: {
        paidAmount: string;
        paidAt: string;
    };
    buildingSafetyForm: {
        siteId: string;
        itemType: BuildingSafetyItemType;
        name: string;
        nextDueDate: string;
        lastCheckedAt: string;
        status: BuildingSafetyItemStatus;
        notes: string;
    };
    duerpForm: {
        siteId: string;
        workUnitName: string;
        riskLabel: string;
        severity: DuerpSeverity;
        preventionAction: string;
    };
    regulatoryEvidenceForm: {
        linkKind: RegulatoryEvidenceLinkKind;
        obligationId: string;
        siteId: string;
        buildingSafetyItemId: string;
        duerpEntryId: string;
        fileName: string;
        documentType: string;
        notes: string;
    };
    private homePageTemplateRef?;
    private reglementationPageTemplateRef?;
    private chantierPageTemplateRef?;
    private facturationPageTemplateRef?;
    private coordinationPageTemplateRef?;
    readonly boundRegulatoryShowcaseActionBusy: (action: {
        actionKind: RegulatoryShowcaseActionKind;
        siteId: string | null;
    }) => boolean;
    readonly boundRegulatoryShowcaseActionLabel: (action: {
        actionKind: RegulatoryShowcaseActionKind;
        actionLabel: string;
        siteId: string | null;
    }) => string;
    constructor();
    getWorkspaceTemplate(name: WorkspaceTemplateName): TemplateRef<unknown> | null;
    ngDoCheck(): void;
    get currentMembership(): MembershipAccess | null;
    get activeSessionModules(): ModuleCode[];
    get shouldRenderLoginScreen(): boolean;
    get canManageModules(): boolean;
    get canManageOrganization(): boolean;
    get canReadOrganization(): boolean;
    get canReadUsers(): boolean;
    get desktopNavigationItems(): Array<{
        route: string;
        label: string;
        tone: CfmTone;
    }>;
    get isReglementationEnabled(): boolean;
    get isFacturationEnabled(): boolean;
    get isChantierEnabled(): boolean;
    get homeUsedModuleCodes(): ModuleCode[];
    get isWorkspaceHydratedForCurrentOrganization(): boolean;
    get isReglementationDataPending(): boolean;
    get isReglementationDataDelayed(): boolean;
    get regulatoryWorkspaceNotice(): string | null;
    get isFacturationDataPending(): boolean;
    get isChantierDataPending(): boolean;
    getModuleNavigationLabel(moduleCode: ModuleCode): string;
    get hasWorkspaceContent(): boolean;
    get shouldShowWorkspaceContent(): boolean;
    get shouldShowInitialWorkspaceLoading(): boolean;
    get isWorkspaceRefreshing(): boolean;
    get hasBetaFeedbackDraft(): boolean;
    get canCopyBetaFeedback(): boolean;
    get betaFeedbackPreviewText(): string;
    get isOnboardingPending(): boolean;
    get isQualificationQuestionnaireComplete(): boolean;
    get canSubmitOnboarding(): boolean;
    get canCreateSite(): boolean;
    get canSaveCustomer(): boolean;
    get isCustomerEditing(): boolean;
    get filteredBillingCustomers(): BillingCustomerRecord[];
    get customerSearchCountLabel(): string;
    get activeWorksitePreventionPlanPreview(): WorksitePreventionPlanPreview | null;
    getWorksiteAssigneeOptionLabel(assignee: WorksiteAssigneeRecord): string;
    toggleWorksiteCoordination(worksiteId: string): void;
    getWorksiteCoordinationDraft(worksiteId: string): CoordinationDraftForm;
    getWorksiteDocumentCoordinationDraft(documentId: string): CoordinationDraftForm;
    updateWorksiteCoordinationDraft(worksiteId: string, patch: Partial<CoordinationDraftForm>): void;
    updateWorksiteDocumentCoordinationDraft(documentId: string, patch: Partial<CoordinationDraftForm>): void;
    private buildCoordinationDraft;
    private buildDashboardCoordinationState;
    private mapDashboardWorksiteDocumentItem;
    private matchesCoordinationFilters;
    private matchesCoordinationStatusFilter;
    private matchesCoordinationAssigneeFilter;
    private isCoordinationPending;
    get worksiteDocumentFilterOptions(): WorksiteApiSummary[];
    get worksiteDocumentTypeFilterOptions(): Array<{
        value: string;
        label: string;
    }>;
    get filteredWorksiteDocumentItems(): DashboardWorksiteDocumentItem[];
    get filteredDashboardWorksiteOverviewItems(): DashboardWorksiteOverviewItem[];
    get worksiteDocumentCountLabel(): string;
    get worksiteOverviewCountLabel(): string;
    get customerOverviewCountLabel(): string;
    get hasActiveCoordinationFilters(): boolean;
    get canResetWorksitePreventionPlanToInitial(): boolean;
    getWorksiteSignatureOptions(worksiteId: string): WorksiteSignatureRecord[];
    getWorksiteSignatureOptionLabel(signature: WorksiteSignatureRecord): string;
    getWorksiteDocumentActionLabel(document: DashboardWorksiteDocumentItem): string;
    get hasActiveWorksiteDocumentFilters(): boolean;
    get coordinationTodoItems(): DashboardCoordinationTodoItem[];
    get coordinationTodoCountLabel(): string;
    isWorksiteDocumentDownloadBusy(document: DashboardWorksiteDocumentItem): boolean;
    canAdjustWorksiteDocument(document: DashboardWorksiteDocumentItem): boolean;
    hasWorksiteDocumentLinkedItems(document: DashboardWorksiteDocumentItem): boolean;
    getWorksiteDocumentProofCountLabel(count: number): string;
    getWorksiteDocumentFileAvailabilityLabel(document: Pick<WorksiteDocumentRecord, "has_stored_file">): string;
    getWorksiteDocumentFileAvailabilityTone(document: Pick<WorksiteDocumentRecord, "has_stored_file">): CfmTone;
    formatFileSize(sizeBytes: number | null): string | null;
    getWorksiteProofOptions(worksiteId: string): WorksiteProofRecord[];
    getWorksiteProofOptionLabel(proof: WorksiteProofRecord): string;
    resetWorksiteDocumentFilters(): void;
    resetCoordinationFilters(): void;
    focusWorksiteDocuments(worksiteId: string, documentType?: string): void;
    openCoordinationTodoItem(item: DashboardCoordinationTodoItem): void;
    isWorksiteProofLinked(document: DashboardWorksiteDocumentItem, proofId: string): boolean;
    get localDashboardKpis(): DashboardKpiCard[];
    get localDashboardAlerts(): DashboardAlertItem[];
    get dashboardKpis(): DashboardKpiCard[];
    get dashboardAlerts(): DashboardAlertItem[];
    get dashboardEnterpriseOverviewCards(): DashboardPerspectiveCard[];
    get dashboardActions(): DashboardActionItem[];
    get filteredDashboardActions(): DashboardActionItem[];
    get dashboardActionCountLabel(): string;
    get localDashboardEnterpriseOverviewCards(): DashboardPerspectiveCard[];
    get dashboardWorksiteOverviewItems(): DashboardWorksiteOverviewItem[];
    get dashboardCustomerOverviewItems(): DashboardCustomerOverviewItem[];
    get canCreateQuote(): boolean;
    get canSaveQuoteEdit(): boolean;
    get canCreateInvoice(): boolean;
    get canSaveInvoiceEdit(): boolean;
    get hasQuoteDraft(): boolean;
    get hasInvoiceDraft(): boolean;
    get quoteFormTotalCents(): number;
    get invoiceFormTotalCents(): number;
    get quoteEditFormTotalCents(): number;
    get invoiceEditFormTotalCents(): number;
    getQuoteHistory(quoteId: string): AuditLogRecord[];
    getInvoiceHistory(invoiceId: string): AuditLogRecord[];
    getBillingHistoryLabel(log: AuditLogRecord): string;
    getBillingHistoryMeta(log: AuditLogRecord): string;
    get activeOrganizationSites(): OrganizationSiteRecord[];
    get regulatoryAllSites(): RegulatoryAllSiteItem[];
    get canCreateBuildingSafetyItem(): boolean;
    get isBuildingSafetyEditing(): boolean;
    get filteredBuildingSafetyItems(): BuildingSafetyItemRecord[];
    get filteredBuildingSafetyAlerts(): BuildingSafetyAlertRecord[];
    get canSaveDuerpEntry(): boolean;
    get filteredDuerpEntries(): DuerpEntryRecord[];
    get activeBuildingSafetyItems(): BuildingSafetyItemRecord[];
    get selectableBuildingSafetyItems(): BuildingSafetyItemRecord[];
    get activeDuerpEntries(): DuerpEntryRecord[];
    get selectableDuerpEntries(): DuerpEntryRecord[];
    get filteredRegulatoryEvidences(): RegulatoryEvidenceRecord[];
    get regulatoryObligations(): ApplicableRegulatoryObligationRecord[];
    get regulatoryEvidenceAvailableCount(): number;
    get regulatoryEvidenceCoverageCount(): number;
    get regulatoryComplianceScore(): number;
    get regulatoryScoreDrivers(): RegulatoryScoreDriverItem[];
    get regulatoryRecommendedActionsSummary(): string;
    get regulatoryProofSupportSummary(): string;
    get regulatoryShowcaseSummary(): RegulatoryShowcaseSummary;
    get regulatoryPriorityItems(): RegulatoryShowcasePriorityItem[];
    get topRegulatoryPriority(): RegulatoryShowcasePriorityItem | null;
    get regulatoryFamilyCards(): RegulatoryShowcaseFamilyCard[];
    get regulatoryRecommendedActions(): RegulatoryShowcaseActionItem[];
    get regulatoryEvidenceShowcaseItems(): RegulatoryShowcaseEvidenceItem[];
    get selectedRegulatoryObligation(): ApplicableRegulatoryObligationRecord | null;
    get selectedObligationCriteria(): RegulatoryCriterionRecord[];
    get selectedObligationEvidences(): RegulatoryEvidenceRecord[];
    getRegulatoryShowcaseActionLabel(action: {
        actionKind: RegulatoryShowcaseActionKind;
        actionLabel: string;
        siteId: string | null;
    }): string;
    isRegulatoryShowcaseActionBusy(action: {
        actionKind: RegulatoryShowcaseActionKind;
        siteId: string | null;
    }): boolean;
    runRegulatoryShowcaseAction(action: {
        actionKind: RegulatoryShowcaseActionKind;
        sectionId: string;
        obligationId: string | null;
        siteId: string | null;
    }): Promise<void>;
    get canCreateRegulatoryEvidence(): boolean;
    openRegulatoryWorkspaceTarget(sectionId: string, obligationId?: string | null): void;
    get buildingSafetyOverdueCount(): number;
    get buildingSafetyDueSoonCount(): number;
    get buildingSafetyOkCount(): number;
    get globalBuildingSafetyOverdueCount(): number;
    get activeQuotesCount(): number;
    get pendingInvoicesCount(): number;
    get overdueInvoicesCount(): number;
    get quotesToFollowUpCount(): number;
    get regulatoryObligationsToVerifyCount(): number;
    get overdueRegulatoryObligationCount(): number;
    get regulatoryActionCount(): number;
    get blockedWorksitesCount(): number;
    get plannedWorksitesCount(): number;
    get worksitesNeedingActionCount(): number;
    submitLogin(): Promise<void>;
    changeOrganization(): Promise<void>;
    copyBetaFeedback(): Promise<void>;
    resetBetaFeedback(): void;
    toggleModule(moduleCode: ModuleCode, nextValue: boolean): Promise<void>;
    completeOnboarding(): Promise<void>;
    saveQualificationQuestionnaire(): Promise<void>;
    saveProfile(successMessage?: string): Promise<void>;
    createSite(): Promise<void>;
    startEditingCustomer(customer: BillingCustomerRecord): void;
    cancelCustomerEditing(): void;
    saveCustomer(): Promise<void>;
    addQuoteLine(): void;
    removeQuoteLine(index: number): void;
    startEditingQuote(quote: QuoteRecord): void;
    cancelQuoteEditing(): void;
    addQuoteEditLine(): void;
    removeQuoteEditLine(index: number): void;
    saveQuoteEdit(quote: QuoteRecord): Promise<void>;
    addInvoiceLine(): void;
    removeInvoiceLine(index: number): void;
    startEditingInvoice(invoice: InvoiceRecord): void;
    cancelInvoiceEditing(): void;
    addInvoiceEditLine(): void;
    removeInvoiceEditLine(index: number): void;
    saveInvoiceEdit(invoice: InvoiceRecord): Promise<void>;
    discardQuoteDraft(): void;
    saveQuote(): Promise<void>;
    exportWorksiteSummaryPdf(worksiteId: string): Promise<void>;
    exportWorksitePreventionPlanPdf(worksiteId: string): Promise<void>;
    downloadWorksiteDocument(document: DashboardWorksiteDocumentItem): Promise<void>;
    toggleWorksiteDocumentDetails(documentId: string): void;
    private markWorksiteDocumentAsStored;
    saveWorksiteCoordination(item: DashboardWorksiteOverviewItem): Promise<void>;
    saveWorksiteDocumentCoordination(document: DashboardWorksiteDocumentItem): Promise<void>;
    changeWorksiteDocumentLifecycleStatus(documentId: string, lifecycleStatus: DocumentLifecycleStatus): Promise<void>;
    changeWorksiteDocumentSignature(documentId: string, signatureDocumentId: string): Promise<void>;
    toggleWorksiteDocumentProof(documentId: string, proofDocumentId: string, isLinked: boolean): Promise<void>;
    toggleWorksitePreventionPlanEditor(worksiteId: string): void;
    cancelWorksitePreventionPlanEditing(): void;
    restoreInitialWorksitePreventionPlanForm(): void;
    exportAdjustedWorksitePreventionPlanPdf(worksiteId: string): Promise<void>;
    prepareQuoteFromWorksite(worksiteId: string): void;
    prepareInvoiceFromWorksite(worksiteId: string): void;
    prepareQuoteFromCustomer(customerId: string): void;
    prepareInvoiceFromCustomer(customerId: string): void;
    changeQuoteWorksite(quote: QuoteRecord, worksiteId: string): Promise<void>;
    exportQuotePdf(quote: QuoteRecord): Promise<void>;
    duplicateQuoteAsInvoice(quote: QuoteRecord): Promise<void>;
    toggleQuoteHistory(quote: QuoteRecord): Promise<void>;
    changeQuoteStatus(quote: QuoteRecord, status: QuoteStatus): Promise<void>;
    changeQuoteFollowUpStatus(quote: QuoteRecord, followUpStatus: BillingFollowUpStatus): Promise<void>;
    discardInvoiceDraft(): void;
    saveInvoice(): Promise<void>;
    changeInvoiceWorksite(invoice: InvoiceRecord, worksiteId: string): Promise<void>;
    exportInvoicePdf(invoice: InvoiceRecord): Promise<void>;
    toggleInvoiceHistory(invoice: InvoiceRecord): Promise<void>;
    changeInvoiceStatus(invoice: InvoiceRecord, status: "draft" | "issued"): Promise<void>;
    changeInvoiceFollowUpStatus(invoice: InvoiceRecord, followUpStatus: BillingFollowUpStatus): Promise<void>;
    openInvoicePayment(invoice: InvoiceRecord): void;
    cancelInvoicePayment(): void;
    canSaveInvoicePayment(invoice: InvoiceRecord): boolean;
    saveInvoicePayment(invoice: InvoiceRecord): Promise<void>;
    startEditingBuildingSafetyItem(item: BuildingSafetyItemRecord): void;
    cancelBuildingSafetyEditing(): void;
    saveBuildingSafetyItem(): Promise<void>;
    toggleBuildingSafetyItemStatus(item: BuildingSafetyItemRecord): Promise<void>;
    startEditingDuerpEntry(entry: DuerpEntryRecord): void;
    cancelDuerpEditing(): void;
    saveDuerpEntry(): Promise<void>;
    toggleDuerpEntryStatus(entry: DuerpEntryRecord): Promise<void>;
    createEvidence(): Promise<void>;
    exportRegulatoryPdf(): Promise<void>;
    toggleSiteStatus(site: OrganizationSiteRecord): Promise<void>;
    relaunchSiteEnrichment(site: OrganizationSiteRecord): Promise<void>;
    openHomeSiteQuickCreate(): void;
    closeHomeSiteQuickCreate(): void;
    handleSiteFilterChange(): void;
    logout(): void;
    getSiteTypeLabel(siteType: OrganizationSiteType): string;
    getSiteEnrichmentUiState(site: OrganizationSiteRecord): DesktopHomeSiteEnrichmentState;
    getSiteEnrichmentReasonLabel(reason: OrganizationSiteLocationEnrichmentErrorReason | null | undefined): string | null;
    getSiteEnrichmentFeedbackMessage(site: OrganizationSiteRecord, created?: boolean): string;
    getSiteNameById(siteId: string | null): string;
    getRegulatoryAllSiteSourceLabel(site: RegulatoryAllSiteItem): string;
    getRegulatoryAllSiteDetail(site: RegulatoryAllSiteItem): string;
    getBillingWorksiteNameById(worksiteId: string | null): string;
    getCustomerTypeLabel(customerType: BillingCustomerType): string;
    getWorksiteStatusLabel(status: WorksiteApiSummary["status"]): string;
    getWorksiteStatusTone(status: WorksiteApiSummary["status"]): CfmTone;
    getWorksiteDocumentLifecycleStatusLabel(status: DocumentLifecycleStatus): string;
    getWorksiteDocumentLifecycleStatusTone(status: DocumentLifecycleStatus): CfmTone;
    getWorksiteDocumentTechnicalStatusLabel(status: RegulatoryEvidenceRecord["status"]): string;
    getWorksiteDocumentTechnicalStatusTone(status: RegulatoryEvidenceRecord["status"]): CfmTone;
    getWorksiteCoordinationStatusLabel(status: WorksiteCoordinationStatus): string;
    getWorksiteCoordinationStatusTone(status: WorksiteCoordinationStatus): CfmTone;
    getWorksiteDocumentSignatureStatusLabel(signatureId: string | null): string;
    getWorksiteDocumentSignatureStatusTone(signatureId: string | null): CfmTone;
    isWorksiteSummaryDocumentType(documentType: string): boolean;
    isWorksitePreventionPlanDocumentType(documentType: string): boolean;
    formatWorksiteLinkedSignatureDetail(document: WorksiteDocumentRecord): string | null;
    mapLinkedWorksiteSignatureItem(document: WorksiteDocumentRecord): DashboardWorksiteLinkedAssetItem | null;
    mapLinkedWorksiteProofItems(document: WorksiteDocumentRecord): DashboardWorksiteLinkedAssetItem[];
    formatWorksiteLinkedProofsSummary(document: WorksiteDocumentRecord): string | null;
    formatWorksiteProofDetail(proof: WorksiteProofRecord): string | null;
    getQuoteStatusLabel(status: QuoteStatus): string;
    getQuoteStatusTone(status: QuoteStatus): CfmTone;
    getInvoiceStatusLabel(status: InvoiceStatus): string;
    getInvoiceStatusTone(status: InvoiceStatus): CfmTone;
    getBillingFollowUpStatusLabel(status: BillingFollowUpStatus): string;
    getBillingFollowUpStatusTone(status: BillingFollowUpStatus): CfmTone;
    getDashboardActionPriorityLabel(priority: DashboardActionPriority): string;
    getDashboardActionPriorityTone(priority: DashboardActionPriority): CfmTone;
    getDashboardActionModuleLabel(module: DashboardActionModule): string;
    getDashboardActionModuleTone(module: DashboardActionModule): CfmTone;
    getBetaFeedbackCategoryLabel(category: BetaFeedbackCategory): string;
    getBetaFeedbackAreaLabel(area: BetaFeedbackArea): string;
    private getDashboardActionPriorityRank;
    private getDashboardOverviewSignalRank;
    private getCoordinationStatusRank;
    private formatDashboardDocumentSummary;
    private formatCompactDate;
    formatAmountCents(amountCents: number, currency?: string): string;
    private getAuditChangeValue;
    private getAuditScalarValue;
    private isQuoteStatus;
    private isInvoiceStatus;
    private isBillingFollowUpStatus;
    private mapCockpitTone;
    getBuildingSafetyTypeLabel(itemType: BuildingSafetyItemType): string;
    getBuildingSafetyAlertStatusLabel(alertStatus: BuildingSafetyItemRecord["alert_status"]): string;
    getBuildingSafetyAlertStatusTone(alertStatus: BuildingSafetyItemRecord["alert_status"]): CfmTone;
    getBuildingSafetySummaryLabel(kind: "overdue" | "due_soon" | "ok"): string;
    getObligationCountLabel(): string;
    getRegulatoryFamilyLabel(category: RegulatoryObligationCategory): string;
    openObligationDetail(obligationId: string): void;
    getObligationCategoryLabel(category: RegulatoryObligationCategory): string;
    getObligationPriorityLabel(priority: RegulatoryObligationPriority): string;
    getObligationPriorityTone(priority: RegulatoryObligationPriority): CfmTone;
    getComplianceStatusLabel(status: ComplianceStatus): string;
    getComplianceStatusTone(status: ComplianceStatus): CfmTone;
    getDocumentStatusLabel(status: RegulatoryEvidenceRecord["status"]): string;
    getDocumentStatusTone(status: RegulatoryEvidenceRecord["status"]): CfmTone;
    getObligationFirstAction(obligation: ApplicableRegulatoryObligationRecord, evidenceCount: number): string;
    getDuerpSeverityLabel(severity: DuerpSeverity): string;
    getDuerpSeverityTone(severity: DuerpSeverity): CfmTone;
    getRegulatoryEvidenceLinkKindLabel(kind: RegulatoryEvidenceLinkKind): string;
    getCriterionTone(value: boolean | number | null): CfmTone;
    private getRegulatoryBooleanCriterion;
    private getRegulatorySiteDedupKey;
    private getRegulatorySiteSourceKindLabel;
    private getProblematicRegulatorySite;
    private getHighestPriorityDuerpEntry;
    private getNextEvidenceGapObligation;
    private getRegulatoryObligationAction;
    private getRegulatoryShowcaseActionGroupKey;
    private buildRegulatoryPriorityCandidates;
    private getRegulatoryFamilyEmptyDetail;
    private getRegulatorySiteInsight;
    private getRegulatoryObligationRank;
    private scrollToWorkspaceSection;
    private refreshSession;
    private clearScheduledWorkspaceRefresh;
    private scheduleWorkspaceRefresh;
    private resolveWorkspaceRequest;
    private refreshOrganizationWorkspace;
    private refreshOrganizationWorkspaceSafely;
    private refreshRegulatoryProfile;
    private refreshBuildingSafetyState;
    private applyProfileToForm;
    private buildProfilePayload;
    private sortSites;
    private resetSiteForm;
    private normalizeOptionalText;
    private persistBillingDraftsIfNeeded;
    private refreshBillingDraftSnapshots;
    private hydrateBillingDraftsIfNeeded;
    private getBillingDraftHydrationScope;
    private getBillingDraftScopeKey;
    private getBillingDraftStorageKey;
    private getBillingDraftStorage;
    private readBillingDraft;
    private saveBillingDraft;
    private clearBillingDraft;
    private buildQuoteDraftPayload;
    private buildInvoiceDraftPayload;
    private restoreQuoteDraft;
    private restoreInvoiceDraft;
    private sanitizeQuoteDraft;
    private sanitizeInvoiceDraft;
    private sanitizeBillingLines;
    private cloneBillingLines;
    private isMeaningfulQuoteDraft;
    private isMeaningfulInvoiceDraft;
    private isMeaningfulBillingLine;
    private hasBillingCustomer;
    private hasBillingWorksite;
    private findBillingCustomerByName;
    private findSingleWorksiteForCustomer;
    private buildWorksitePreventionPlanForm;
    private cloneWorksitePreventionPlanForm;
    private buildWorksitePreventionPlanPreview;
    private buildDefaultWorksitePreventionContext;
    private buildDefaultWorksiteVigilancePoints;
    private buildDefaultWorksiteMeasurePoints;
    private splitMultilineItems;
    private toSearchableText;
    private toDateTimeLocalValue;
    private formatDateTimeForHumans;
    private scrollToDesktopSection;
    private navigateToWorkspaceRoute;
    private handleRouteChange;
    private resetWorkspaceState;
    private clearWorkspaceSegmentIssue;
    private setWorkspaceSegmentIssue;
    private toWorkspaceSegmentIssueMessage;
    private ensureAccessibleWorkspaceRoute;
    private isLoginRoutePath;
    private isShellRoutePath;
    private clearAuthenticatedState;
    private isModuleDataPending;
    private buildBetaFeedbackPayload;
    private copyTextToClipboard;
    private toErrorMessage;
    private toApiClientErrorMessage;
    private isLikelyNetworkErrorMessage;
    private isUserFacingErrorMessage;
    private getDefaultErrorMessage;
    private getValidationErrorMessage;
    private getNetworkErrorMessage;
    private getTemporaryUnavailableMessage;
    private downloadBlob;
    private getTodayDateValue;
    private createEmptyQuoteForm;
    private createEmptyInvoiceForm;
    private createEmptyWorksitePreventionPlanForm;
    private buildQuoteFormFromRecord;
    private buildInvoiceFormFromRecord;
    private createEmptyBillingLineForm;
    private parseBillingQuantity;
    private parseUnitPriceToCents;
    private hasValidBillingLines;
    private computeBillingFormTotalCents;
    private buildBillingLineItemsPayload;
    private resetCustomerForm;
    private resetQuoteForm;
    private resetInvoiceForm;
    private resetWorksitePreventionPlanForm;
    private resetInvoicePaymentForm;
    private resetDuerpForm;
    private resetBuildingSafetyForm;
    private resetRegulatoryEvidenceForm;
    static ɵfac: i0.ɵɵFactoryDeclaration<AppComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<AppComponent, "cfm-root", never, {}, {}, never, never, true, never>;
}
export {};
//# sourceMappingURL=app.component.d.ts.map